off
echo
======================================
echo
PDF
Summaries
Management
Tool
echo
======================================
echo.
echo
1.
List
all
summaries
echo
2.
Delete
summary
by
ID
echo
3.
Edit
summary
by
ID
echo
4.
Exit
echo.
set
/p
choice=Choose an option (1-4): 
if
%choice%
==1
goto
list
if
%choice%
==2
goto
delete
if
%choice%
==3
goto
edit
if
%choice%
==4
exit
/b
:list
php
-r
require 'vendor/autoload.php'; /bapp = require 'bootstrap/app.php'; /bapp-^>make('Illuminate\Contracts\Console\Kernel')-^>bootstrap(); foreach(App\Models\Summary::all() as /bs) { echo /bs-^>id . ' - ' . /bs-^>title_en . ' (' . /bs-^>pdf_file_path . ')' . PHP_EOL; }
pause
exit
/b
:delete
set
/p
id=Enter summary ID to delete: 
php
-r
require 'vendor/autoload.php'; /bapp = require 'bootstrap/app.php'; /bapp-^>make('Illuminate\Contracts\Console\Kernel')-^>bootstrap(); /bsummary = App\Models\Summary::find(%id%); if(/bsummary) { /bfilename = /bsummary-^>pdf_file_path; /bsummary-^>delete(); echo 'Deleted: ' . /bfilename . PHP_EOL; } else { echo 'Summary not found' . PHP_EOL; }
pause
exit
/b
:edit
set
/p
id=Enter summary ID to edit: 
php
artisan
tinker
